//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Company.RICT.RICTDiagram")]

namespace Company.RICT
{
	/// <summary>
	/// DomainClass RICTDiagram
	/// Description for Company.RICT.RICTDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Company.RICT.RICTDiagram.DisplayName", typeof(global::Company.RICT.RICTDomainModel), "Company.RICT.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.RICT.RICTDiagram.Description", typeof(global::Company.RICT.RICTDomainModel), "Company.RICT.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.RICT.RICTDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("56a9e2ff-a21e-462c-972e-d268befba243")]
	public partial class RICTDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Company.RICT.RICTToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Company.RICT.SystemicLevel)
			{
				global::Company.RICT.sSystematicLevel newShape = new global::Company.RICT.sSystematicLevel(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.EnablingLevel)
			{
				global::Company.RICT.sEnablingLevel newShape = new global::Company.RICT.sEnablingLevel(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.ImmediateLevel)
			{
				global::Company.RICT.sImmediateLevel newShape = new global::Company.RICT.sImmediateLevel(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.SocialConcern)
			{
				global::Company.RICT.sSocialConcern newShape = new global::Company.RICT.sSocialConcern(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.TechnicalConcern)
			{
				global::Company.RICT.sTechnicalConcern newShape = new global::Company.RICT.sTechnicalConcern(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.EnvironmentalConcern)
			{
				global::Company.RICT.sEnvironmentalConcern newShape = new global::Company.RICT.sEnvironmentalConcern(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.EconomicConcern)
			{
				global::Company.RICT.sEconomicConcern newShape = new global::Company.RICT.sEconomicConcern(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.Concern)
			{
				global::Company.RICT.sConcern newShape = new global::Company.RICT.sConcern(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.SoftwareArchitecture)
			{
				global::Company.RICT.sSoftwareArchitecture newShape = new global::Company.RICT.sSoftwareArchitecture(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.RICT.UndecidedEffectConcern)
			{
				global::Company.RICT.sUndecidedEffect newShape = new global::Company.RICT.sUndecidedEffect(this.Partition);
				return newShape;
			}
			if(element is global::Company.RICT.UndecidedEffectSA)
			{
				global::Company.RICT.sUndecidedEffect newShape = new global::Company.RICT.sUndecidedEffect(this.Partition);
				return newShape;
			}
			if(element is global::Company.RICT.PositiveEffectSA)
			{
				global::Company.RICT.sPositiveEffect newShape = new global::Company.RICT.sPositiveEffect(this.Partition);
				return newShape;
			}
			if(element is global::Company.RICT.NegativeEffectSA)
			{
				global::Company.RICT.sNegativeEffect newShape = new global::Company.RICT.sNegativeEffect(this.Partition);
				return newShape;
			}
			if(element is global::Company.RICT.PositiveEffectConcern)
			{
				global::Company.RICT.sPositiveEffect newShape = new global::Company.RICT.sPositiveEffect(this.Partition);
				return newShape;
			}
			if(element is global::Company.RICT.NegativeEffectConcern)
			{
				global::Company.RICT.sNegativeEffect newShape = new global::Company.RICT.sNegativeEffect(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Company.RICT.sConcern.DecoratorsInitialized += sConcernDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sSocialConcern.DecoratorsInitialized += sSocialConcernDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sTechnicalConcern.DecoratorsInitialized += sTechnicalConcernDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sEnvironmentalConcern.DecoratorsInitialized += sEnvironmentalConcernDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sEconomicConcern.DecoratorsInitialized += sEconomicConcernDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sImmediateLevel.DecoratorsInitialized += sImmediateLevelDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sEnablingLevel.DecoratorsInitialized += sEnablingLevelDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sSystematicLevel.DecoratorsInitialized += sSystematicLevelDecoratorMap.OnDecoratorsInitialized;
			global::Company.RICT.sSoftwareArchitecture.DecoratorsInitialized += sSoftwareArchitectureDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sConcern.
		/// </summary>
		internal static partial class sConcernDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sConcern.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.Concern.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.Concern.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.Concern.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sSocialConcern.
		/// </summary>
		internal static partial class sSocialConcernDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sSocialConcern.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				sConcernDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sTechnicalConcern.
		/// </summary>
		internal static partial class sTechnicalConcernDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sTechnicalConcern.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				sConcernDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sEnvironmentalConcern.
		/// </summary>
		internal static partial class sEnvironmentalConcernDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sEnvironmentalConcern.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				sConcernDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sEconomicConcern.
		/// </summary>
		internal static partial class sEconomicConcernDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sEconomicConcern.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				sConcernDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sImmediateLevel.
		/// </summary>
		internal static partial class sImmediateLevelDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sImmediateLevel.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sEnablingLevel.
		/// </summary>
		internal static partial class sEnablingLevelDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sEnablingLevel.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sSystematicLevel.
		/// </summary>
		internal static partial class sSystematicLevelDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sSystematicLevel.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.ImpactLevel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for sSoftwareArchitecture.
		/// </summary>
		internal static partial class sSoftwareArchitectureDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for sSoftwareArchitecture.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.SoftwareArchitecture.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.SoftwareArchitecture.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.RICT.SoftwareArchitecture.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::Company.RICT.UndecidedEffectConcernConnectAction undecidedEffectConcernConnectAction;
		private global::Company.RICT.PositiveEffectConcernConnectAction positiveEffectConcernConnectAction;
		private global::Company.RICT.NegativeEffectConcernConnectAction negativeEffectConcernConnectAction;
		private global::Company.RICT.UndecidedEffectSAConnectAction undecidedEffectSAConnectAction;
		private global::Company.RICT.PositiveEffectSAConnectAction positiveEffectSAConnectAction;
		private global::Company.RICT.NegativeEffectSAConnectAction negativeEffectSAConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.RICT.RICTToolboxHelper.UndecidedEffectConcernFilterString))
				{
					if (this.undecidedEffectConcernConnectAction == null)
					{
						this.undecidedEffectConcernConnectAction = new global::Company.RICT.UndecidedEffectConcernConnectAction(this);
						this.undecidedEffectConcernConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.undecidedEffectConcernConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.RICT.RICTToolboxHelper.PositiveEffectConcernFilterString))
				{
					if (this.positiveEffectConcernConnectAction == null)
					{
						this.positiveEffectConcernConnectAction = new global::Company.RICT.PositiveEffectConcernConnectAction(this);
						this.positiveEffectConcernConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.positiveEffectConcernConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.RICT.RICTToolboxHelper.NegativeEffectConcernFilterString))
				{
					if (this.negativeEffectConcernConnectAction == null)
					{
						this.negativeEffectConcernConnectAction = new global::Company.RICT.NegativeEffectConcernConnectAction(this);
						this.negativeEffectConcernConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.negativeEffectConcernConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.RICT.RICTToolboxHelper.UndecidedEffectSAFilterString))
				{
					if (this.undecidedEffectSAConnectAction == null)
					{
						this.undecidedEffectSAConnectAction = new global::Company.RICT.UndecidedEffectSAConnectAction(this);
						this.undecidedEffectSAConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.undecidedEffectSAConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.RICT.RICTToolboxHelper.PositiveEffectSAFilterString))
				{
					if (this.positiveEffectSAConnectAction == null)
					{
						this.positiveEffectSAConnectAction = new global::Company.RICT.PositiveEffectSAConnectAction(this);
						this.positiveEffectSAConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.positiveEffectSAConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.RICT.RICTToolboxHelper.NegativeEffectSAFilterString))
				{
					if (this.negativeEffectSAConnectAction == null)
					{
						this.negativeEffectSAConnectAction = new global::Company.RICT.NegativeEffectSAConnectAction(this);
						this.negativeEffectSAConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.negativeEffectSAConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.undecidedEffectConcernConnectAction != null)
					{
						this.undecidedEffectConcernConnectAction.Dispose();
						this.undecidedEffectConcernConnectAction = null;
					}
					if(this.positiveEffectConcernConnectAction != null)
					{
						this.positiveEffectConcernConnectAction.Dispose();
						this.positiveEffectConcernConnectAction = null;
					}
					if(this.negativeEffectConcernConnectAction != null)
					{
						this.negativeEffectConcernConnectAction.Dispose();
						this.negativeEffectConcernConnectAction = null;
					}
					if(this.undecidedEffectSAConnectAction != null)
					{
						this.undecidedEffectSAConnectAction.Dispose();
						this.undecidedEffectSAConnectAction = null;
					}
					if(this.positiveEffectSAConnectAction != null)
					{
						this.positiveEffectSAConnectAction.Dispose();
						this.positiveEffectSAConnectAction = null;
					}
					if(this.negativeEffectSAConnectAction != null)
					{
						this.negativeEffectSAConnectAction.Dispose();
						this.negativeEffectSAConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// RICTDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x56a9e2ff, 0xa21e, 0x462c, 0x97, 0x2e, 0xd2, 0x68, 0xbe, 0xfb, 0xa2, 0x43);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RICTDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RICTDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Company.RICT
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Company.RICT.SystemicLevel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.EnablingLevel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.ImmediateLevel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.SocialConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.TechnicalConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.EnvironmentalConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.EconomicConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.Concern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.SoftwareArchitecture), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.UndecidedEffectConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.UndecidedEffectSA), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.PositiveEffectSA), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.NegativeEffectSA), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.PositiveEffectConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.NegativeEffectConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::Company.RICT.SystemicLevel)
				{
					parentElement = GetParentForSystemicLevel((global::Company.RICT.SystemicLevel)childElement);
				} else
				if(childElement is global::Company.RICT.EnablingLevel)
				{
					parentElement = GetParentForEnablingLevel((global::Company.RICT.EnablingLevel)childElement);
				} else
				if(childElement is global::Company.RICT.ImmediateLevel)
				{
					parentElement = GetParentForImmediateLevel((global::Company.RICT.ImmediateLevel)childElement);
				} else
				if(childElement is global::Company.RICT.SocialConcern)
				{
					parentElement = GetParentForSocialConcern((global::Company.RICT.SocialConcern)childElement);
				} else
				if(childElement is global::Company.RICT.TechnicalConcern)
				{
					parentElement = GetParentForTechnicalConcern((global::Company.RICT.TechnicalConcern)childElement);
				} else
				if(childElement is global::Company.RICT.EnvironmentalConcern)
				{
					parentElement = GetParentForEnvironmentalConcern((global::Company.RICT.EnvironmentalConcern)childElement);
				} else
				if(childElement is global::Company.RICT.EconomicConcern)
				{
					parentElement = GetParentForEconomicConcern((global::Company.RICT.EconomicConcern)childElement);
				} else
				if(childElement is global::Company.RICT.Concern)
				{
					parentElement = GetParentForConcern((global::Company.RICT.Concern)childElement);
				} else
				if(childElement is global::Company.RICT.SoftwareArchitecture)
				{
					parentElement = GetParentForSoftwareArchitecture((global::Company.RICT.SoftwareArchitecture)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Company.RICT.SoSA GetParentForConcern( global::Company.RICT.Concern root )
			{
				// Segments 0 and 1
				global::Company.RICT.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.RICT.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForSystemicLevel( global::Company.RICT.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.RICT.SoSA result = root.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForEnablingLevel( global::Company.RICT.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.RICT.SoSA result = root.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForSoftwareArchitecture( global::Company.RICT.SoftwareArchitecture root )
			{
				// Segments 0 and 1
				global::Company.RICT.ImpactLevel root2 = root.ImmediateLevel as global::Company.RICT.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.RICT.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForImmediateLevel( global::Company.RICT.ImpactLevel root )
			{
				// Segments 0 and 1
				global::Company.RICT.SoSA result = root.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForSocialConcern( global::Company.RICT.Concern root )
			{
				// Segments 0 and 1
				global::Company.RICT.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.RICT.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForTechnicalConcern( global::Company.RICT.Concern root )
			{
				// Segments 0 and 1
				global::Company.RICT.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.RICT.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForEnvironmentalConcern( global::Company.RICT.Concern root )
			{
				// Segments 0 and 1
				global::Company.RICT.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.RICT.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.RICT.SoSA GetParentForEconomicConcern( global::Company.RICT.Concern root )
			{
				// Segments 0 and 1
				global::Company.RICT.ImpactLevel root2 = root.ImpactLevel;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.RICT.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Company.RICT.UndecidedEffectConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.UndecidedEffectSA), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.PositiveEffectSA), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.NegativeEffectSA), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.PositiveEffectConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.RICT.NegativeEffectConcern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::Company.RICT.RICTDiagram diagram = linkShape.Diagram as global::Company.RICT.RICTDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
