//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace Company.RICT
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Concern
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateConcernMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.SoftwareArchitecture1 == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.RICT.RICTDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Concern", this.Name, "SoftwareArchitecture1"),
						"DSL0001", this);
			}
			if (this.SoftwareArchitecture2 == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.RICT.RICTDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Concern", this.Name, "SoftwareArchitecture2"),
						"DSL0001", this);
			}
			if (this.SoftwareArchitecture3 == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.RICT.RICTDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Concern", this.Name, "SoftwareArchitecture3"),
						"DSL0001", this);
			}
		} // ValidateConcernMultiplicity
	} // class Concern
} // Company.RICT

	
 