//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.RICT
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "RICT";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"RICT";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RICTDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RICTCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RICTExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RICTCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRICTExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RICTCommandSetId), 0x0001);
	
		// Package identifier
		public const string RICTPackageId = "c7b3220a-5c52-4811-abbb-367090ad33d5";
		
		// Editor factory identifier
		public const string RICTEditorFactoryId = "37c615f5-af59-45bb-b179-d29833a24d69";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RICTModelExplorerToolWindowId = "75f0fd49-f745-4474-ba1e-ed6c9353d9ee";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.RICT
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RICTCommandSetId = "aca2067d-4831-4fb6-9268-cc9dd21ccc07";
	}
}